const test = require("node:test")
const assert = require("node:assert/strict")

const UserDirs = require("../UserDirs.js")

test("uses friendly names for standard and custom directory keys", () => {
  assert.equal(UserDirs.displayName("DOWNLOAD"), "Downloads")
  assert.equal(UserDirs.displayName("PUBLICSHARE"), "Public Share")
  assert.equal(UserDirs.displayName("PROJECT_ARCHIVE"), "Project Archive")
})

test("unquotes the escapes supported by user-dirs.dirs", () => {
  assert.equal(UserDirs.unquote('"$HOME/a\\\"b\\\\c\\$d\\`e"'), '$HOME/a"b\\c$d`e')
})

test("parses absolute and HOME-relative directories in file order", () => {
  const raw = [
    "# Generated by xdg-user-dirs-update",
    'XDG_DOWNLOAD_DIR="$HOME/Downloads"',
    'XDG_PUBLICSHARE_DIR="$HOME/Public Share"',
    'XDG_ARCHIVE_DIR="/srv/archive"'
  ].join("\n")

  assert.deepEqual(UserDirs.parseUserDirs(raw, "/home/test"), [
    { name: "Downloads", path: "/home/test/Downloads" },
    { name: "Public Share", path: "/home/test/Public Share" },
    { name: "Archive", path: "/srv/archive" }
  ])
})

test("skips home, relative, malformed, and duplicate directory entries", () => {
  const raw = [
    'XDG_DESKTOP_DIR="$HOME/"',
    'XDG_DOWNLOAD_DIR="$HOME/Downloads"',
    'XDG_DOCUMENTS_DIR="$HOME/Downloads"',
    'XDG_RELATIVE_DIR="relative/path"',
    'NOT_AN_XDG_ENTRY="$HOME/Other"'
  ].join("\n")

  assert.deepEqual(UserDirs.parseUserDirs(raw, "/home/test"), [
    { name: "Downloads", path: "/home/test/Downloads" }
  ])
})
